import {
  SunIcon, MoonIcon, FlashlightIcon, CircleDotIcon, SkullIcon,
  WaveIcon, DivingMaskIcon, SunsetIcon, DolphinIcon, WhaleIcon,
  SquidIcon, SharkIcon, FishIcon, CoralIcon, ShipIcon, GlobeIcon,
  SubmarineIcon, MapPinIcon, TurtleIcon, ShellIcon
} from "../../assets/Icons";

// ─── Dữ liệu các vùng đại dương ─────────────────────────────────────────────
export const OCEAN_ZONES = [
  {
    id: "sunlight",
    nameVi: "Vùng Ánh Sáng",
    nameEn: "Sunlight Zone",
    subNameVi: "Epipelagic",
    subNameEn: "Epipelagic",
    depthStart: 0,
    depthEnd: 200,
    colorFrom: "#0ea5e9",
    colorTo: "#0284c7",
    bgClass: "from-[#0ea5e9]/20 to-[#0369a1]/20",
    descVi:
      "Ánh sáng mặt trời xuyên qua hoàn toàn. Nơi sinh sống của hầu hết các loài sinh vật biển. Nồng độ oxy tốt, nhiệt độ ổn định, quang hợp diễn ra mạnh mẽ.",
    descEn:
      "Full sunlight penetrates this zone. Home to most marine life. High oxygen levels, stable temperatures, and active photosynthesis.",
    icon: SunIcon,
    pressure: "1–20 atm",
    temp: "0–30°C",
    light: "100%",
    visibility: "Tốt (>30m)",
    oxygen: "Cao (7–8 mg/L)",
  },
  {
    id: "twilight",
    nameVi: "Vùng Chạng Vạng",
    nameEn: "Twilight Zone",
    subNameVi: "Mesopelagic",
    subNameEn: "Mesopelagic",
    depthStart: 200,
    depthEnd: 1000,
    colorFrom: "#1e40af",
    colorTo: "#1e3a8a",
    bgClass: "from-[#1e40af]/20 to-[#1e3a8a]/20",
    descVi:
      "Ánh sáng mờ dần. Nhiều loài có khả năng phát quang sinh học. Nơi nhiều loài di cư theo chiều thẳng đứng mỗi ngày để kiếm ăn.",
    descEn:
      "Faint light penetrates here. Many species have bioluminescence. Vertical migrators feed here at night.",
    icon: MoonIcon,
    pressure: "20–100 atm",
    temp: "4–20°C",
    light: "1%",
    visibility: "Yếu (<5m)",
    oxygen: "Thấp (2–4 mg/L)",
  },
  {
    id: "midnight",
    nameVi: "Vùng Nửa Đêm",
    nameEn: "Midnight Zone",
    subNameVi: "Bathypelagic",
    subNameEn: "Bathypelagic",
    depthStart: 1000,
    depthEnd: 4000,
    colorFrom: "#1e1b4b",
    colorTo: "#312e81",
    bgClass: "from-[#1e1b4b]/20 to-[#312e81]/20",
    descVi:
      "Bóng tối hoàn toàn. Áp suất khổng lồ. Sinh vật kỳ dị với răng trong suốt, mắt phát sáng và bẫy đèn bioluminescent.",
    descEn:
      "Complete darkness. Enormous pressure. Strange creatures with transparent teeth, glowing eyes, and bioluminescent lures.",
    icon: FlashlightIcon,
    pressure: "100–400 atm",
    temp: "2–4°C",
    light: "0%",
    visibility: "Không có",
    oxygen: "Rất thấp (1–2 mg/L)",
  },
  {
    id: "abyss",
    nameVi: "Vùng Vực Thẳm",
    nameEn: "Abyssal Zone",
    subNameVi: "Abyssopelagic",
    subNameEn: "Abyssopelagic",
    depthStart: 4000,
    depthEnd: 6000,
    colorFrom: "#0f0a2e",
    colorTo: "#0a0520",
    bgClass: "from-[#0f0a2e]/20 to-[#0a0520]/20",
    descVi:
      "Tầng vực thẳm. Nền đáy lạnh giá và đen tối. Các sinh vật kỳ lạ ăn mảnh vụn hữu cơ rơi từ tầng trên.",
    descEn:
      "The abyss. Cold, dark seafloor. Bizarre creatures feed on marine snow falling from above.",
    icon: CircleDotIcon,
    pressure: "400–600 atm",
    temp: "0–2°C",
    light: "0%",
    visibility: "Không có",
    oxygen: "Cực thấp (<1 mg/L)",
  },
  {
    id: "hadal",
    nameVi: "Vùng Siêu Vực",
    nameEn: "Hadal Zone",
    subNameVi: "Hadalpelagic",
    subNameEn: "Hadalpelagic",
    depthStart: 6000,
    depthEnd: 11034,
    colorFrom: "#050211",
    colorTo: "#020108",
    bgClass: "from-[#050211]/20 to-[#020108]/20",
    descVi:
      "Rãnh đại dương sâu nhất. Áp suất nghiền nát. Chỉ vài loài đặc biệt có thể tồn tại ở đây — vi khuẩn, giun ống, và tôm Amphipod.",
    descEn:
      "The deepest ocean trenches. Crushing pressure. Only a handful of species survive — bacteria, tube worms, and Amphipod shrimp.",
    icon: SkullIcon,
    pressure: "600–1100 atm",
    temp: "1–2°C",
    light: "0%",
    visibility: "Không có",
    oxygen: "Biến đổi",
  },
];

// ─── Các mốc landmark nổi bật ────────────────────────────────────────────────
export const DEPTH_LANDMARKS = [
  {
    depth: 0,
    icon: WaveIcon,
    labelVi: "Mực nước biển",
    labelEn: "Sea Level",
    descVi: "Ranh giới giữa đại dương và khí quyển",
    descEn: "Boundary between ocean and atmosphere",
    color: "#38bdf8",
  },
  {
    depth: 40,
    icon: DivingMaskIcon,
    labelVi: "Giới hạn lặn tự do",
    labelEn: "Free Diving Limit",
    descVi: "Độ sâu tối đa người có thể lặn tự do mà không có thiết bị hỗ trợ",
    descEn:
      "Maximum depth humans can free dive without equipment under normal conditions",
    color: "#34d399",
  },
  {
    depth: 200,
    icon: SunsetIcon,
    labelVi: "Giới hạn ánh sáng",
    labelEn: "Photic Zone End",
    descVi: "Ranh giới cuối cùng ánh sáng mặt trời có thể xuyên qua",
    descEn: "The last depth sunlight can penetrate",
    color: "#fbbf24",
  },
  {
    depth: 300,
    icon: DolphinIcon,
    labelVi: "Cá heo lặn",
    labelEn: "Dolphin Dive Depth",
    descVi: "Độ sâu lặn tối đa của cá heo mỏ vịt",
    descEn: "Maximum diving depth of bottlenose dolphins",
    color: "#60a5fa",
  },
  {
    depth: 500,
    icon: WhaleIcon,
    labelVi: "Cá voi lưng gù",
    labelEn: "Humpback Whale",
    descVi: "Độ sâu lặn tối đa của cá voi lưng gù",
    descEn: "Maximum diving depth of humpback whales",
    color: "#818cf8",
  },
  {
    depth: 1000,
    icon: SquidIcon,
    labelVi: "Mực khổng lồ",
    labelEn: "Giant Squid Zone",
    descVi: "Môi trường sống của mực khổng lồ",
    descEn: "Habitat of the giant squid",
    color: "#c084fc",
  },
  {
    depth: 1300,
    icon: SharkIcon,
    labelVi: "Cá mập đầu búa",
    labelEn: "Hammerhead Shark",
    descVi: "Độ sâu săn mồi tối đa của cá mập đầu búa",
    descEn: "Maximum hunting depth of hammerhead sharks",
    color: "#f87171",
  },
  {
    depth: 2000,
    icon: FishIcon,
    labelVi: "Cá đèn lồng",
    labelEn: "Lanternfish Zone",
    descVi: "Sinh vật phát quang sinh học phổ biến nhất đại dương",
    descEn: "Most abundant bioluminescent fish in the ocean",
    color: "#34d399",
  },
  {
    depth: 2500,
    icon: CoralIcon,
    labelVi: "Cá rồng biển",
    labelEn: "Dragonfish Zone",
    descVi: "Cá rồng biển với hàm răng khổng lồ",
    descEn: "Dragonfish with enormous transparent teeth",
    color: "#fb923c",
  },
  {
    depth: 3800,
    icon: ShipIcon,
    labelVi: "Tàu Titanic",
    labelEn: "RMS Titanic",
    descVi: "Vị trí xác tàu Titanic nằm dưới đáy Đại Tây Dương",
    descEn:
      "Location of the Titanic wreck at the bottom of the North Atlantic",
    color: "#94a3b8",
  },
  {
    depth: 4267,
    icon: GlobeIcon,
    labelVi: "Độ sâu trung bình đại dương",
    labelEn: "Average Ocean Depth",
    descVi: "Độ sâu trung bình của tất cả các đại dương trên Trái Đất",
    descEn: "Average depth of all Earth's oceans combined",
    color: "#64748b",
  },
  {
    depth: 6000,
    icon: FishIcon,
    labelVi: "Vực thẳm Hadal bắt đầu",
    labelEn: "Hadal Zone Begins",
    descVi: "Bắt đầu vùng rãnh đại dương sâu nhất thế giới",
    descEn: "Beginning of the world's deepest ocean trenches",
    color: "#a855f7",
  },
  {
    depth: 10928,
    icon: DivingMaskIcon,
    labelVi: "Victor Vescovo lặn",
    labelEn: "Victor Vescovo Dive",
    descVi: "Kỷ lục lặn sâu nhất của con người năm 2019",
    descEn: "Deepest human dive record set in 2019",
    color: "#22d3ee",
  },
  {
    depth: 11034,
    icon: MapPinIcon,
    labelVi: "Rãnh Mariana — Đáy Sâu Nhất",
    labelEn: "Mariana Trench — Deepest Point",
    descVi: "Điểm sâu nhất đại dương trên Trái Đất: Challenger Deep",
    descEn: "The deepest point in Earth's oceans: Challenger Deep",
    color: "#a855f7",
  },
];

// ─── Sinh vật theo độ sâu ────────────────────────────────────────────────────
export const CREATURES_BY_DEPTH = [
  {
    id: "great-white-shark-1",
    depthMin: 0,
    depthMax: 1200,
    nameVi: "Cá Mập Trắng Lớn",
    nameEn: "Great White Shark",
    emoji: SharkIcon,
    descVi: "Kẻ săn mồi đỉnh cao của đại dương",
    descEn: "The ocean's ultimate apex predator",
    tagColor: "#ef4444",
  },
  {
    id: "whale-shark-2",
    depthMin: 0,
    depthMax: 1900,
    nameVi: "Cá Mập Voi Thái Bình Dương",
    nameEn: "Whale Shark",
    emoji: WhaleIcon,
    descVi: "Loài cá lớn nhất trên hành tinh",
    descEn: "The largest fish species on Earth",
    tagColor: "#3b82f6",
  },
  {
    id: "clownfish-4",
    depthMin: 1,
    depthMax: 15,
    nameVi: "Cá Hề San Hô",
    nameEn: "Clown Anemonefish",
    emoji: FishIcon,
    descVi: "Sống cộng sinh với hải quỳ",
    descEn: "Lives symbiotically with sea anemones",
    tagColor: "#f97316",
  },
  {
    id: "sea-turtle-5",
    depthMin: 0,
    depthMax: 100,
    nameVi: "Rùa Xanh Biển Honu",
    nameEn: "Green Sea Turtle",
    emoji: TurtleIcon,
    descVi: "Biểu tượng may mắn của đại dương",
    descEn: "Symbol of good luck in the Pacific",
    tagColor: "#22c55e",
  },
  {
    id: "dolphin-6",
    depthMin: 0,
    depthMax: 300,
    nameVi: "Cá Heo Mỏ Vịt",
    nameEn: "Pacific Bottlenose Dolphin",
    emoji: DolphinIcon,
    descVi: "Loài thông minh với khả năng định vị siêu âm",
    descEn: "Intelligent species with echolocation",
    tagColor: "#06b6d4",
  },
  {
    id: "blue-whale-7",
    depthMin: 0,
    depthMax: 500,
    nameVi: "Cá Voi Xanh Khổng Lồ",
    nameEn: "Pacific Blue Whale",
    emoji: WhaleIcon,
    descVi: "Động vật lớn nhất từng tồn tại",
    descEn: "The largest animal that has ever existed",
    tagColor: "#6366f1",
  },
  {
    id: "bluefin-tuna-1",
    depthMin: 0,
    depthMax: 550,
    nameVi: "Cá Ngừ Vây Xanh",
    nameEn: "Pacific Bluefin Tuna",
    emoji: FishIcon,
    descVi: "Một trong những tay bơi nhanh nhất đại dương",
    descEn: "One of the ocean's fastest swimmers",
    tagColor: "#0ea5e9",
  },
  {
    id: "chambered-nautilus-8",
    depthMin: 100,
    depthMax: 700,
    nameVi: "Ốc Vòi Voi Hóa Thạch Sống",
    nameEn: "Chambered Nautilus",
    emoji: ShellIcon,
    descVi: "Hóa thạch sống 500 triệu năm",
    descEn: "A 500-million-year living fossil",
    tagColor: "#e879f9",
  },
  {
    id: "giant-octopus-3",
    depthMin: 0,
    depthMax: 1500,
    nameVi: "Bạch Tuộc Khổng Lồ",
    nameEn: "Giant Pacific Octopus",
    emoji: SquidIcon,
    descVi: "Sinh vật thông minh bậc nhất đại dương",
    descEn: "The ocean's most intelligent invertebrate",
    tagColor: "#f43f5e",
  },
  {
    id: "mantaray-9",
    depthMin: 0,
    depthMax: 1000,
    nameVi: "Cá Đuối Manta",
    nameEn: "Oceanic Manta Ray",
    emoji: FishIcon,
    descVi: "Bơi lượn như cánh chim trong nước",
    descEn: "Glides gracefully like underwater wings",
    tagColor: "#84cc16",
  },
];
