// Automatically generated by "npm run translate" script
const en = {
  "nav": {
    "explore": "Discover",
    "species": "Sea creatures",
    "about": "About us",
    "quiz": "Game",
    "register": "Register",
    "login": "Log in",
    "language": "Language"
  },
  "hero": {
    "titleLine1": "Explore the World",
    "titleLine2": "Pacific",
    "description": "Journey to experience the mysterious beauty and diverse ecosystem of the world's largest ocean.",
    "btnExplore": "Explore now",
    "btnAbout": "About the Pacific Ocean",
    "stat1Title": "Acreage",
    "stat1Value": "165.2M km²",
    "stat2Title": "Creature",
    "stat2Value": "50,000+ Species",
    "stat3Title": "Maximum depth",
    "stat3Value": "11,034 m"
  },
  "search": {
    "title": "What creature do you want to learn about?",
    "subtitle": "Quickly search for information about Pacific Ocean creatures",
    "placeholder": "Enter creature name (Shark, Octopus, Coral...)",
    "btnSearch": "Search"
  },
  "species": {
    "title": "Outstanding Organisms",
    "subtitle": "Typical representatives of the Pacific ocean",
    "btnViewAll": "See all creatures"
  },
  "about": {
    "badge": "About the Pacific Ocean",
    "title": "The Largest Ocean on Earth",
    "desc1": "The Pacific Ocean accounts for more than 30% of the Earth's surface area, containing tens of thousands of magical species from shallow coral reefs to the mysterious Mariana abyss.",
    "desc2": "Pacific's mission is to connect nature-loving communities, spread marine conservation knowledge and build awareness of ocean environmental protection.",
    "stat1Title": "Miraculous",
    "stat1Value": "165.2 million km²",
    "stat2Title": "Creature",
    "stat2Value": "50,000+ Species",
    "stat3Title": "Maximum depth",
    "stat3Value": "11,034 m"
  },
  "footer": {
    "brandDesc": "Explore the magical ocean world, home to countless mysteries and amazing creatures of the Pacific.",
    "exploreTitle": "Discover",
    "legalTitle": "Policy & Terms",
    "privacyPolicy": "Information security",
    "termsOfUse": "Terms of use",
    "contentPolicy": "Content policy",
    "contactTitle": "Contribute comments",
    "contactDesc": "Please share your thoughts!",
    "feedbackPlaceholder": "Ask and say the way you think...",
    "btnSendFeedback": "Send comments",
    "copyright": "© 2026 Pacific. All rights reserved."
  },
  "auth": {
    "loginTitle": "Log in",
    "loginSubtitle": "Welcome back! Please enter information.",
    "registerTitle": "Register",
    "registerSubtitle": "Let's create an account for yourself!",
    "fullName": "Full name",
    "email": "E-mail",
    "password": "Password",
    "confirmPassword": "Confirm password",
    "rememberMe": "Remember to log in",
    "forgotPassword": "Forgot password?",
    "btnLogin": "Log in",
    "btnRegister": "Register",
    "orWith": "or",
    "orLoginWith": "or log in with",
    "noAccount": "Don't have an account yet?",
    "hasAccount": "Already have an account?",
    "registerNow": "Register now",
    "loginNow": "Sign in now",
    "brandTitle": "Explore the magical ocean world",
    "brandDesc": "Fully experience the journey to learn about hundreds of rich marine creatures.",
    "registerBadge": "Join Pacific",
    "registerBrandTitle": "Start your ocean journey today",
    "registerBrandDesc": "Create a free account to keep your quiz history and track your progress in discovering marine life.",
    "feature1": "Look up diversity",
    "feature1Sub": "Data on hundreds of biological species",
    "feature2": "Vivid quizzes",
    "feature2Sub": "Discover the ocean's personality",
    "feature3": "Information security",
    "feature3Sub": "Absolute safety for your account",
    "featurePersonalized": "Personalized experience",
    "featurePersonalizedSub": "Save test information",
    "featureCommunity": "Community connection",
    "featureCommunitySub": "Contribute and discuss knowledge"
  }
};

export default en;
