import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const VI_FILE = path.join(__dirname, "../src/locales/vi.js");
const EN_FILE = path.join(__dirname, "../src/locales/en.js");

// Google Translate Free Endpoint
async function translateText(text) {
  if (!text || typeof text !== "string") return text;
  try {
    const url = `https://translate.googleapis.com/translate_a/single?client=gtx&sl=vi&tl=en&dt=t&q=${encodeURIComponent(text)}`;
    const res = await fetch(url);
    const data = await res.json();
    if (data && data[0] && Array.isArray(data[0])) {
      return data[0].map((item) => item[0]).join("");
    }
  } catch (err) {
    console.error(`Error translating "${text}":`, err.message);
  }
  return text;
}

// Recursively traverse & translate object
async function translateObject(obj) {
  const result = {};
  for (const key of Object.keys(obj)) {
    const val = obj[key];
    if (typeof val === "object" && val !== null && !Array.isArray(val)) {
      result[key] = await translateObject(val);
    } else if (typeof val === "string") {
      process.stdout.write(`Translating: "${val.slice(0, 30)}..." -> `);
      const translated = await translateText(val);
      console.log(`"${translated.slice(0, 30)}..."`);
      result[key] = translated;
    } else {
      result[key] = val;
    }
  }
  return result;
}

async function run() {
  console.log("🚀 Starting Auto Translation from vi.js to en.js...\n");

  try {
    // Dynamically import vi.js
    const viModule = await import(`file://${VI_FILE}`);
    const viData = viModule.default;

    const translatedEn = await translateObject(viData);

    const fileContent = `// Automatically generated by "npm run translate" script\nconst en = ${JSON.stringify(
      translatedEn,
      null,
      2
    )};\n\nexport default en;\n`;

    fs.writeFileSync(EN_FILE, fileContent, "utf-8");
    console.log("\n✅ Auto translation completed! Updated src/locales/en.js successfully.");
  } catch (err) {
    console.error("❌ Translation failed:", err);
  }
}

run();
